import {
  LayoutDashboard, Users, GitBranch, Home, CheckSquare, Star,
  MessageCircle, Map, BarChart3, QrCode, ScrollText, User, Settings,
  Search, Bell, Plus, Upload, Download, Pencil, Trash2, X, XCircle, Check,
  Phone, Mail, Calendar, AlertTriangle, AlertCircle, ChevronDown, ChevronRight,
  ChevronLeft, LogOut, Filter, ArrowRight, ArrowUpRight, Clock,
  Send, Repeat, CheckCircle2, BookOpen, Droplet, Sparkles, Crown,
  UserPlus, Heart, Smartphone, FileText, Circle, Pause, RefreshCw,
  Flag, LifeBuoy, Footprints, Building2, Compass, GraduationCap,
  Wallet, Utensils, Car, Briefcase, Accessibility, Frown, Stethoscope,
  ShieldAlert, Lock, ArrowLeft, MapPin, ChevronUp, MessageSquare, Tag, HelpCircle, Save,
  Target, TrendingUp, TrendingDown, RotateCcw, HeartHandshake, CalendarDays
} from 'lucide-react'
export const NAV_ICON_MAP = {
  dashboard: LayoutDashboard,
  accueil: Calendar,
  visiteurs: Users,
  'fiches-a-completer': AlertTriangle,
  pipeline: GitBranch,
  fi: Home,
  suivi: CheckSquare,
  jeunesse: Star,
  communications: MessageCircle,
  planning: CalendarDays,
  carte: Map,
  rapports: BarChart3,
  qrcode: QrCode,
  journal: ScrollText,
  utilisateurs: User,
  validations: CheckSquare,
  parametres: Settings,
}
export const STAGE_ICON_MAP = {
  visiteur: Users,
  contacte: Phone,
  invite_fi: Send,
  fi1: Home,
  fi2: Repeat,
  integre: CheckCircle2,
  parcours: BookOpen,
  bapteme: Droplet,
  service: Sparkles,
  leader_pot: Star,
  leader: Crown,
}
export const FI_STATUS_ICON_MAP = {
  en_developpement: RefreshCw,
  active: CheckCircle2,
  en_pause: Pause,
  fermee: XCircle,
}
export const JOURNAL_TYPE_ICON_MAP = {
  priere: Heart,
  besoin: LifeBuoy,
  difficulte: AlertTriangle,
  remarque: MessageCircle,
  action: CheckCircle2,
  decision: Flag,
}
export const CONTACT_METHOD_ICON_MAP = {
  appel: Phone,
  telephone: Phone,
  whatsapp: MessageCircle,
  sms: Smartphone,
  visite: Footprints,
  rencontre_culte: Building2,
  audio: Phone,
  autre: FileText,
}
export const NEED_ICON_MAP = {
  nouveau_converti: Sparkles,
  reconciliation: Users,
  demande_bapteme: Droplet,
  besoin_accompagnement: Compass,
  sujet_priere: Heart,
  solitude: User,
  parent_isole: User,
  etudiant: GraduationCap,
  difficulte_financiere: Wallet,
  difficulte_alimentaire: Utensils,
  difficulte_logement: Home,
  difficulte_transport: Car,
  recherche_emploi: Briefcase,
  recherche_formation: BookOpen,
  handicap: Accessibility,
  depression: Frown,
  maladie: Stethoscope,
  addiction: AlertTriangle,
  violence_familiale: ShieldAlert,
  besoin_fi: Home,
  besoin_mentor: UserPlus,
  autre: FileText,
}
export {
  Search, Bell, Plus, Upload, Download, Pencil, Trash2, X, XCircle, Check,
  Phone, Mail, Calendar, AlertTriangle, AlertCircle, ChevronDown, ChevronRight,
  ChevronLeft, LogOut, Filter, ArrowRight, ArrowUpRight, Clock,
  Settings, Users, Home, MessageCircle, Star, GitBranch, BarChart3, CheckSquare,
  Send, Repeat, CheckCircle2, BookOpen, Droplet, Sparkles, Crown,
  UserPlus, Heart, Smartphone, FileText, Circle, Pause, RefreshCw,
  Flag, LifeBuoy, Footprints, Building2, Compass, GraduationCap,
  Wallet, Utensils, Car, Briefcase, Accessibility, Frown, Stethoscope,
  ShieldAlert, Lock, ArrowLeft, MapPin, ChevronUp, LayoutDashboard,
  MessageSquare, Tag, HelpCircle, Save,
  Target, TrendingUp, TrendingDown, RotateCcw, HeartHandshake, CalendarDays
}
